backend:
  name: github
  repo: denis-zaichenko/csm-test

media_folder: static/assets
public_folder: /assets

collections:
  - name: aboutUs
    label: About Us
    folder: src/markdown/start-page
    create: true
    fields:
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - label: "Paragraphs"
        name: "paragraphs"
        widget: "list"
        field: { label: Paragraph, name: paragraph, widget: string }
